"""create users table

Revision ID: 19844f6836d3
Revises: 
Create Date: 2026-09-20 11:36:47.444992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19844f6836d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table("users",
            sa.Column("id",
            sa.Integer(),nullable=False),
            sa.Column("email",
            sa.String(length=255),
            nullable=False),
            
            sa.Column("password_hash",
            sa.String(length=255),
            nullable=False
        ),
        
        sa.Column("is_active",
                  sa.Boolean(), nullable=False),
        
        sa.Column("created-at",
                  sa.DateTime(),nullable=False),
        
        sa.PrimaryKeyConstraint("id")
        
    )
    op.create_index(
        "ix-users_id",
        "users",
        ["id"],
        unique=False,
    )
    
    op.create_index(
            "ix-users_email",
            "users",
            ["email"],
            unique=True,
        )
    
    
    
    # """Upgrade schema."""
    # # ### commands auto generated by Alembic - please adjust! ###
    # pass
    # # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index("ix_users_email",
                  table_name="users")
    
    op.drop_index("ix_users_id",
                  table_name="users")
    
    op.drop_table("users")
    # """Downgrade schema."""
    # # ### commands auto generated by Alembic - please adjust! ###
    # pass
    # # ### end Alembic commands ###
